### PR TITLE
Added events for the glyphs and their definitions.

### PR DESCRIPTION
**Pull request by Morfium-G**

### CODE REVIEW

**Comment by ihm-tswow** [comment]
It looks like this commit changed the entirety of both `TSEvents.h` and `global.d.ts` so I can't see what actually changed in them. This sometimes happens if you applied a different line ending encoding (though usually git will automatically fix this). What git version or tool did you use to create these commits?

**Comment by Morfium-G** [comment]
Oh... didn't notice that. I used sourcetree to commit and git via command line to push. Seems like it didn't convert back to LF.

**Comment by Morfium-G** [comment]
Also here's a sample lifescript to set max level for glyphs to 60. Should not require any client changes. The only issue is that the locked glyphs on lower levels will still show the old levels for their unlock. It's likely just a  gluestring.
```
events.Player.OnGlyphInitForLevel((player: TSPlayer, enabledGlyphs: TSMutable<uint32>) => {
        const level = player.GetLevel();
        let value = 0;
        if (level >= 15)
            value |= (0x01 | 0x02);
        if (level >= 30)
            value |= 0x08;
        if (level >= 50)
            value |= 0x04;
        if (level >= 60)
            value |= 0x10;
        if (level >= 60)
            value |= 0x20;
        
        console.log('OnGlyphInit - returning value is: ', value);
        enabledGlyphs.set(value);
    });
    
    events.Player.OnEffectApplyGlyphIsLocked((glyphIndex: uint32, isLocked: TSMutable<boolean>, player: TSPlayer) => {
        
        const level = player.GetLevel();
        switch (glyphIndex)
        {
            case 0:
            case 1: isLocked.set(level < 15); break;
            case 2: isLocked.set(level < 50); break;
            case 3: isLocked.set(level < 30); break;
            case 4: isLocked.set(level < 60); break;
            case 5: isLocked.set(level < 60); break;
        }
        console.log('OnEffectApplyGlyph - returning value is: ', isLocked.get());
    });
```

**Comment by ihm-tswow** [comment]
Thanks for the pull!

**Pull request merged**
