### PR TITLE
OnCalcMiss

### PR DESCRIPTION
**Pull request by TesterWoWDev**

### CODE REVIEW

**Comment by ihm-tswow** [comment]
the miss parameter should use the auto-generated enum for SpellMissInfo as the parameter type in the global.d.ts (but not in the C++ files), you can look at the other enums at the top of the file for how we generate them

**Comment by TesterWoWDev** [comment]
added as enum: [048cc15](https://github.com/tswow/tswow/pull/544/commits/048cc15f634e2328fdaf8dae7d608d04b1d4e919)
and updated to master:[445204a](https://github.com/tswow/tswow/pull/544/commits/445204a2f5e3e50c217dcaf7484d3b38f1727c33)

**Comment by ihm-tswow** [comment]
I think crushing/glancing should not be put into the OnCalcMeleeOutcome event for two reasons:

1. It breaks the existing API by moving the attackType argument back (and putting the new parameters last would be very ugly)
2. It makes those calculations happen for every melee outcome, including those that aren't even valid for crushing/glancing. This both wastes calculations and leads to weird behaviors for scripters who try to modify them (i.e. trying to always turn it on, seeing the event fire for every outcome but still only applying to some of them)

**Comment by TesterWoWDev** [comment]
1. yeah the ordering was mostly just to keep chance next to chance 
2. i didnt make it separate for the reason of if somebody for some reason wanted to modify the melee events it seemed odd to force 2 events for the same use case, modifying chances. Yes glance/crush does have separate checks(level and skill) but is that not something that is up to a scripter to understand?

**Comment by ihm-tswow** [comment]
I still don't agree, the core doesn't calculate those for every melee outcome, so we shouldn't force it to just to fit the existing event, especially if it can't even be used in most outcomes. There are many different calculation events like these, and having worked with them I usually end up having to hook at least 4 or 5 different ones anyways.

An additional benefit of having these as separate events is that you can also extend them without breaking the api to do something like override the level check itself: `Unit::OnCalcCrushing(chance)` -> `Unit::OnCalcCrushing(chance, skipLevelCheck)`. This wouldn't need to be a part of the event from the start, but would be possible to make as a future extension. It could also be its own separate event, which would make even less sense if the chance was already calculated in the previous event.

**Pull request closed without merging**
