### PR TITLE
livescripts: add TSGUID class

### PR DESCRIPTION
**Pull request by ihm-tswow**
adds a new class to handle guids without relying on raw uint64s

### CODE REVIEW

**Comment by kaytotes** [comment]
```ts
    events.Player.OnLogin((player) => {
        const guid = player.GetGUID();

        player.SetUInt('stored', guid.GetLow());

        player.AddTimer(1000, TimerLoops.ONCE, 0, (owner) => {
            const _p = owner.ToPlayer();

            const _guid = _p.GetGUID();
            const _stored = _p.GetUInt('stored', 0);

            console.log(`\nGUID: ${_guid}\n`)
            console.log(`\nStored: ${_stored}\n`)

            const found = _p.GetPlayer(_stored);
            if (! found.IsNull())
                console.log(`\nUsed to get ${found.GetName()}!\n`);
        });
    });
```

```
error C2819: type 'TSGUID' does not have an overloaded member 'operator ->'
```

```cpp
player->SetUInt(std::string("stored"), guid->GetLow());
```

**Comment by kaytotes** [comment]
One thing I'm not quite clear of with this is how we actually store a guid and get it with this method. Normally I'd use `entity.SetUInt64('thing', player.GetGUID())` but that doesn't seem to be possible with this and trying to explicitly cast to uint64 didn't work.

**Comment by ihm-tswow** [comment]
had to think about this a little, I think the right solution is to have `SetGUID` methods to ensure stuff like JSON serialization doesn't break

**Comment by ihm-tswow** [comment]
i added these as `GetGUIDNumber` / `SetGUIDNumber` to not confuse them with Objects own `GetGUID` method

**Comment by ihm-tswow** [comment]
been testing this and seems to work as intended in lua/c++, and don't seem to cause any noticable regressions. if there are further issues we can fix them in future merges

**Pull request merged**
