### PR TITLE
get all players function

### PR DESCRIPTION
**Pull request by TesterWoWDev**

### CODE REVIEW

**Comment by ihm-tswow** [comment]
This is not safe even with a mutex, you will end up fighting other map threads for modifying the player objects. This should be added to the `TSMapManager` class so you can use it from delayed events (or the World.OnUpdate event)

```ts
    events.Player.OnSay((x)=>{
       // Entity-bound main-thread event
        x.DoDelayed((player,mgr)=>{
            mgr.GetAllPlayers();
        })

       // Map-bound delayed/main thread event
        x.GetMap().DoDelayed((map,mgr)=>{
            mgr.GetAllPlayers();
        })
    })

    // Unbound delayed/main thread event
    events.World.OnUpdate((diff,mgr) => {
        mgr.GetAllPlayers();
    });
```

**Comment by TesterWoWDev** [comment]
Wouldn't this be no different than the Eluna version of GetPlayersInWorld or when players are iterated for saves by the object accessor class?
https://github.com/ElunaLuaEngine/Eluna/blob/c63c9b38be7053793c0d10ae4e5895c029b288bd/GlobalMethods.h#L181
https://github.com/TrinityCore/TrinityCore/blob/bceb5b606068b8ef29a55338bcaa8fb611be4e33/src/server/game/Globals/ObjectAccessor.cpp#L267

**Comment by ihm-tswow** [comment]
Eluna forces map updates to be single-threaded because lua itself doesn't support multithreading. Livescripts can be multithreaded, so it is not safe to access data from other maps outside of delayed (synchronous) events.

The "SaveAllPlayers" command is similarly single-threaded, because server commands happen on the main thread.

**Comment by ihm-tswow** [comment]
Just to clarify, the purpose of the `TSMapManager` class is to only expose server-wide functionality to events that happen on the main thread. It is still missing from some events, like command handlers, and is currently broken on the master branch.

**Comment by TesterWoWDev** [comment]
Well i can copy this over to the TSMapManager and give it a shot here over the weekend when i get some time to compile the dev branch.

**Comment by ihm-tswow** [comment]
If you think there is a good reason to allow doing that synchronously from a livescript where you promise you're only running single-threaded there could be a global `UnsafeGlobals` call or something that returns a TSMapMgr from anywhere and throws an error if the server is running multithreaded

**Comment by TesterWoWDev** [comment]
I think that only would come up if you're already running the lua suite which would have it's own function for this already. I suppose there is a time where you could be working in a team of developers, which would already have eluna turned on, setting it to the single map thread.

**Comment by TesterWoWDev** [comment]
PR #643 is the replacement PR

**Pull request closed without merging**
