### PR TITLE
DK runes for any classes

### PR DESCRIPTION
**Pull request by TesterWoWDev**
requires table in world db:
class_has_runes
hasRune should be 0 or 1
struct:
```
DROP TABLE IF EXISTS `class_has_runes`;
CREATE TABLE `class_has_runes`  (
  `classID` int(11) NOT NULL,
  `hasRune` int(11) NOT NULL,
  PRIMARY KEY (`classID`) USING BTREE
) ENGINE = InnoDB CHARACTER SET = latin1 COLLATE = latin1_swedish_ci ROW_FORMAT = Dynamic;
```

Also requires a small UI modification in Interface\FrameXML\RuneFrame
line 109 checks if not dk, will require adding your own class or some new type of check here

### CODE REVIEW

**Comment by TesterWoWDev** [comment]
also no clue how it edited talents and PlayerOnTalentsResetEarly events, i guess the git merge picked up some old code.

**Comment by ihm-tswow** [comment]
## Boolean field
The "hasRune" field is not needed, instead the startup script should just check what entries exist in this table and ignore those that don't. This avoid the duplicate definition of "entry x = false" being equivalent to missing entry x.

## Masks
`std::map` is an inefficient way to check for class ids, you should build a mask instead:

```c++
uint32 classmask = 0;
for(uint32 class_id in your db table)
{
    classmask |= (1<<(class_id-1));
}
```

Then this is & compared against the players classmask during a check, see next section

## Racemasks

Class/race checks that can check both class/race generally should. Binary operations are extremely efficient and gives users a lot more options. I think this makes sense here even if the resource bar itself is hard per class normally, mostly to make it future-proof in the datascript api.

- add a column for race and make it a primary key
- add default entries in that table for death knight and all races (ids 1 through 32)
- Now you can do your core check with `Unit::MatchRaceClassMask` (make sure to set third argument to false)

## Datascripts

Existance of this field in the database should probably be wrapped in a boolean cell in datascripts like this: 

```ts
YOUR_CLASS
    .Races.forEach(x=>x
        .UseRunes.set(true) // this is a fake boolean, we delete/undelete a row when it changes
    )
```

I think there are few people that have attempted to do this kind of black magic cell, and the ClassRace struct is especially complicated, so I can probably do that part, but you're welcome to try if you want a challenge.

## Automatically generate RuneFrame

Similarly to other class ui fields, we can use datascripts luaxml to automatically generate this. I think the sensible place to do it would be a "finish" event, since we probably want to hardcode a value based on all the final values in the table. This is probably also on the complicated side, but you can check the class ui modules for how we modify luaxml if you want a challenge.

**Comment by ihm-tswow** [comment]
(ignore azerothcore failures, i'm going to disable it since it's stale, if we resume development it'll be much easier to just fix these things in batch)

**Comment by TesterWoWDev** [comment]
I've been building only trinitycore, so works for me.
 ill implement the masking here real quick since that 1 seems pretty quick to implement. 

ill have to look into the UI and datascript additions, but that will take a bit more research and take more time compared to the mask change.

**Comment by ihm-tswow** [comment]
just lmk if you want help with datascripts/ui, they're probably on the harder side, and I could prolly get it done pretty fast

**Comment by TesterWoWDev** [comment]
Since the race mask would require placing into some array of classID already, what do you think about adding a boolean to PlayerInfo that defaults false? ex 
`if (sObjectMgr->GetPlayerInfo(GetRace(),GetClass()).hasRune)`

**Comment by ihm-tswow** [comment]
racemask should not require placing into any kind of array, you build all the class ids into one single classmask and all the race ids into one single racemask, then you send that racemask/classmask pair with Unit::MatchRaceClassMask

**Comment by TesterWoWDev** [comment]
How would you build the racemask in respect to the classID? Since the classmask and racemask is built on startup when iterating the db, utilizing only a single racemask would always be true since dk has all races.

**Comment by ihm-tswow** [comment]
yeah nevermind, i'm an idiot, it's a racemask per class id of course. store racemasks in an array indexed by class id, hardcode the arrya size to 32

**Comment by TesterWoWDev** [comment]
class/racemask commit - also still no clue what git is smoking today to somehow say i edited ac

**Comment by TesterWoWDev** [comment]
After looking into it yes i do believe that is black magic and i think ill need some assistance on the datascript part/luaxml part.

**Comment by TesterWoWDev** [comment]
also found out that runic power gen/degen was also in this commit. so this also makes it possible to gen/degen runic power, but you still need to do a SetMaxPower(1000 + bonus) in a livescript to give the starting/

**Comment by ihm-tswow** [comment]
@TesterWoWDev try out my changes with some different races and classes, i only tried the datascript side of it. You can now enable/disable both the server tables and client ui from `ClassRacePairs`:

```ts
std.Classes.load(SOME_CLASS)
    .Races.forEach(x=>{
        x.HasRunes.set(true|false)
    })
```

**Comment by TesterWoWDev** [comment]
DK runes show without any datascript changes

undead race_id is actually 'Scourge', which caused initial problems showing but found that 1
All race strings:
Human", "NightElf", "Dwarf", "Gnome", "Draenei", "Orc", "Troll", "Scourge", "Tauren", "BloodElf"

running the std.Class.load snippit does make the required UI modification to show the runes on a blizzlike
running the std.Class.load snippit does make the required UI modification to show the runes on a custom class

DK is now not showing runes when utilizing the class.load on a custom class

(later found that it is replacing)
image
with
image
It would need to or the classes together rather than replacement

**Comment by TesterWoWDev** [comment]
last commit did fix undead, however there is still only 1 class shown 

however, if i put both dk and custom class in datascripts, it does do it correctly.

ex not working.
image
image

ex. working
image
image

**Comment by TesterWoWDev** [comment]
Also just as a concise way, it might be best to have the races anded to a group of all of the classes or'd together rather than each class having it's own set of races (or is this so that some classes could have a per-race rune show rather than all races?)
ex.
`(not ((class_id == "CUSTOMCLASS" or class_id == "DEATHKNIGHT") and (race_id == "Human" or race_id == "Orc" or race_id == "Dwarf" or race_id == "NightElf" or race_id == "Scourge" or race_id == "Tauren" or race_id == "Gnome" or race_id == "Troll" or race_id == "BloodElf" or race_id == "Draenei")))`

**Comment by ihm-tswow** [comment]
That doesn't work, since each class maps to a list of allowed races, as in some classes can permit that race while others forbid them. It seems like the overwriting is caused by another issue which i'm not sure is even in this module, but i'll investigate

**Comment by ihm-tswow** [comment]
(but yes, the or clauses is really ugly, didn't bother with anything prettier because i think a "real" solution should use something else entirely)

**Comment by TesterWoWDev** [comment]
latest commit solves the class issue, so it all seems to be working now

**Pull request merged**
